{
    "openapi": "3.0.0",
    "info": {
      "title": "Developer API Documentation",
      "version": "1.0.0",
      "description": "API documentation for your project"
    },
    "servers": [
      {
        "url": "http://localhost:3000",
        "description": "Development server"
      }
    ],
    "paths": {
      "/api/v1/user/register": {
        "post": {
          "summary": "Register a new user",
          "tags": ["User"],
          "requestBody": {
            "required": true,
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/definitions/User"
                }              
              }
            }
          },
          "responses": {
            "201": {
              "description": "User created successfully",
              "content": {
                "application/json": {
                  "examples": {
                    "success": {
                      "summary": "Example of a successful response",
                      "value": {
                        "message": "User created successfully",
                        "result": {
                          "id": 5,
                          "firstName": "John",
                          "lastName": "Doe",
                          "email": "john.doe3@example.com",
                          "phone": "1234567890",
                          "createdAt": "2024-07-10T13:45:27.487Z",
                          "updatedAt": "2024-07-10T13:45:27.487Z"
                        }
                      }
                    }
                  }
                }
              }
            },
            "400": {
              "description": "Bad request",
              "content": {
                "application/json": {
                  "examples": {
                    "error": {
                      "summary": "Example of an error response",
                      "value": {
                        "status": "fail",
                        "errors": [
                          {
                            "field": "email",
                            "message": "Email is already in use",
                            "location": "body"
                          }
                        ]
                      }
                    }
                  }
                }
              }
            }
          }
        }
      },
    "/api/v1/user/{id}": {      
      "get": {
        "summary": "Get user by ID",
        "description": "Endpoint to retrieve a user by ID",
        "tags": ["User"],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "integer"
          }
        ],
        "responses": {
          "200": {
            "description": "User found",
            "content": {
                "application/json": {
                  "examples": {
                    "success": {
                      "summary": "Example of a successful response",
                      "value": {
                        "message": "User data fetched successfully",
                        "result": {
                          "id": 5,
                          "firstName": "John",
                          "lastName": "Doe",
                          "email": "john.doe3@example.com",
                          "phone": "1234567890",
                          "createdAt": "2024-07-10T13:45:27.487Z",
                          "updatedAt": "2024-07-10T13:45:27.487Z"
                        }
                      }
                    }
                  }
                }
              }
          },
          "404": {
            "description": "User not found"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      },
      "put": {
        "tags": [
          "User"
        ],
        "summary": "Update an existing user",
        "description": "Updates a user with the given ID.",
        "operationId": "updateUser",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "description": "ID of the user to update",
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          }          
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/definitions/User"
              }              
            }
          }
        },
        "responses": {
          "200": {
            "description": "User updated successfully",
            "schema": {
              "$ref": "#/definitions/UserResponse"
            },
            "examples": {
              "application/json": {
                "message": "User updated successfully",
                "result": {
                  "id": 1,
                  "firstName": "John",
                  "lastName": "Doe",
                  "email": "john.doe@example.com",
                  "phone": "1234567890",
                  "createdAt": "2024-07-10T11:59:56.412Z",
                  "updatedAt": "2024-07-10T11:59:56.412Z"
                }
              }
            }
          },
          "400": {
            "description": "Invalid input",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "404": {
            "description": "User not found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/api/v1/user/all": {
      "get": {
        "tags": ["User"],
        "summary": "Get all users",
        "description": "Retrieve all users",
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
                "application/json": {
                  "examples": {
                    "success": {
                      "summary": "Example of a successful response",
                      "value": {
                        "message": "User data fetched successfully",
                        "result": [
                          {
                          "id": 5,
                          "firstName": "John",
                          "lastName": "Doe",
                          "email": "john.doe3@example.com",
                          "phone": "1234567890",
                          "createdAt": "2024-07-10T13:45:27.487Z",
                          "updatedAt": "2024-07-10T13:45:27.487Z"
                          },
                          {
                          "id": 6,
                          "firstName": "John",
                          "lastName": "Doe",
                          "email": "john.doe6@example.com",
                          "phone": "1234567890",
                          "createdAt": "2024-07-10T13:45:27.487Z",
                          "updatedAt": "2024-07-10T13:45:27.487Z"
                          }
                      ]
                      }
                    }
                  }
                }
              }
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    } 
  },
  "definitions": {
    "User": {
      "type": "object",
      "required": [
        "firstName",
        "lastName",
        "email",
        "phone"
      ],
      "properties": {
        "firstName": {
          "type": "string",
          "default": "John"
        },
        "lastName": {
          "type": "string",
          "default": "Doe"
        },
        "email": {
          "type": "string",
          "format": "email",
          "default": "JohnDoe@gmail.com"
        },
        "phone": {
          "type": "string",
          "default": "1234567890"
        },
        "password": {
          "type": "string",
          "default": "123456"
        }
      }
    },
    "UserResponse": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer",
          "format": "int64"
        },
        "firstName": {
          "type": "string",
          "default": "John"
        },
        "lastName": {
          "type": "string"
        },
        "email": {
          "type": "string",
          "format": "email"
        },
        "phone": {
          "type": "string"
        },
        "createdAt": {
          "type": "string",
          "format": "date-time"
        },
        "updatedAt": {
          "type": "string",
          "format": "date-time"
        }
      }
    },
    "Error": {
      "type": "object",
      "properties": {
        "message": {
          "type": "string"
        }
      }
    }
  }
  }
  